## Support Vector Regression Implimentation

In [4]:
## Dataset (Tips Dataset)

import seaborn as sns

df = sns.load_dataset('tips')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [6]:
df['sex'].value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [7]:
df['smoker'].value_counts()

smoker
No     151
Yes     93
Name: count, dtype: int64

In [8]:
df['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [9]:
## Independent and Dependent features

X = df.drop('total_bill', axis=1)
y = df['total_bill']

In [10]:
# Train test split

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=10)

In [11]:
X_train.sample(5)

      tip     sex smoker   day    time  size
1    1.66    Male     No   Sun  Dinner     3
58   1.76    Male    Yes   Sat  Dinner     2
144  2.30  Female     No  Thur   Lunch     2
231  3.00    Male    Yes   Sat  Dinner     3
145  1.50  Female     No  Thur   Lunch     2

In [12]:
## Feature Encoding
# Label Encoding
# One hot encoding

from sklearn.preprocessing import LabelEncoder

le1 = LabelEncoder()
le2 = LabelEncoder()
le3 = LabelEncoder()

In [13]:
X_train['sex'] = le1.fit_transform(X_train['sex'])
X_train['smoker'] = le2.fit_transform(X_train['smoker'])
X_train['time'] = le3.fit_transform(X_train['time'])

X_train.sample(10)

      tip  sex  smoker   day  time  size
73   5.00    0       1   Sat     0     2
15   3.92    1       0   Sun     0     2
203  2.50    0       1  Thur     1     2
28   4.30    1       0   Sat     0     2
164  3.00    0       1   Sun     0     2
75   1.25    1       0   Sat     0     2
179  3.55    1       1   Sun     0     2
0    1.01    0       0   Sun     0     2
11   5.00    0       0   Sun     0     4
118  1.80    0       0  Thur     1     2

In [14]:
X_test['sex'] = le1.transform(X_test['sex'])
X_test['smoker'] = le2.transform(X_test['smoker'])
X_test['time'] = le3.transform(X_test['time'])

X_test.sample(10)

      tip  sex  smoker   day  time  size
61   2.00    1       1   Sat     0     2
162  2.00    0       0   Sun     0     3
195  1.44    1       0  Thur     1     2
226  2.00    0       1   Fri     1     2
120  2.31    1       0  Thur     1     2
219  3.09    0       1   Sat     0     4
46   5.00    1       0   Sun     0     2
214  6.50    0       1   Sat     0     3
211  5.16    1       1   Sat     0     4
127  2.00    0       0  Thur     1     2

In [15]:
## Onehot Encoding --- ColumnTransformer

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [16]:
ct = ColumnTransformer(transformers=[('onehot', OneHotEncoder(drop='first'), [3])], remainder='passthrough')

In [17]:
import sys
import numpy
numpy.set_printoptions(threshold=sys.maxsize)
X_train = ct.fit_transform(X_train)

In [18]:
X_test = ct.transform(X_test)

In [19]:
X_test

array([[0.  , 1.  , 0.  , 2.  , 0.  , 0.  , 0.  , 3.  ],
       [1.  , 0.  , 0.  , 3.21, 1.  , 1.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 2.  , 1.  , 1.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 3.76, 1.  , 1.  , 0.  , 4.  ],
       [1.  , 0.  , 0.  , 2.09, 1.  , 1.  , 0.  , 2.  ],
       [0.  , 0.  , 1.  , 5.  , 1.  , 1.  , 1.  , 2.  ],
       [0.  , 1.  , 0.  , 3.51, 1.  , 0.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 5.16, 1.  , 1.  , 0.  , 4.  ],
       [0.  , 1.  , 0.  , 5.  , 1.  , 0.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 3.6 , 1.  , 0.  , 0.  , 3.  ],
       [0.  , 1.  , 0.  , 5.65, 1.  , 1.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 2.5 , 0.  , 1.  , 0.  , 3.  ],
       [0.  , 0.  , 1.  , 1.44, 1.  , 0.  , 1.  , 2.  ],
       [1.  , 0.  , 0.  , 3.09, 0.  , 1.  , 0.  , 4.  ],
       [0.  , 1.  , 0.  , 2.  , 1.  , 0.  , 0.  , 4.  ],
       [0.  , 0.  , 1.  , 1.36, 0.  , 0.  , 1.  , 3.  ],
       [0.  , 0.  , 1.  , 2.  , 0.  , 0.  , 1.  , 2.  ],
       [0.  , 0.  , 1.  , 1.68, 0.  , 0.  , 1.  , 2.  ],
       [0.  , 1.  , 0.  , 3.5 , 0.  , 1.  , 0.  , 3.  ],
       [1.  , 0.  , 0.  , 3.16, 1.  , 1.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 1.71, 1.  , 0.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 2.5 , 0.  , 1.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 2.  , 1.  , 0.  , 0.  , 2.  ],
       [0.  , 0.  , 1.  , 1.63, 0.  , 0.  , 1.  , 2.  ],
       [0.  , 1.  , 0.  , 5.  , 1.  , 0.  , 0.  , 5.  ],
       [0.  , 0.  , 1.  , 2.  , 0.  , 0.  , 1.  , 2.  ],
       [1.  , 0.  , 0.  , 3.08, 1.  , 1.  , 0.  , 2.  ],
       [0.  , 0.  , 1.  , 2.92, 0.  , 0.  , 1.  , 4.  ],
       [0.  , 0.  , 1.  , 2.31, 1.  , 0.  , 1.  , 2.  ],
       [1.  , 0.  , 0.  , 6.73, 1.  , 0.  , 0.  , 4.  ],
       [0.  , 1.  , 0.  , 5.07, 1.  , 0.  , 0.  , 4.  ],
       [1.  , 0.  , 0.  , 6.5 , 0.  , 1.  , 0.  , 3.  ],
       [0.  , 1.  , 0.  , 2.  , 1.  , 0.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 2.5 , 1.  , 0.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 3.18, 1.  , 0.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 1.1 , 0.  , 1.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 3.35, 1.  , 0.  , 0.  , 3.  ],
       [0.  , 0.  , 0.  , 2.2 , 1.  , 1.  , 1.  , 2.  ],
       [1.  , 0.  , 0.  , 4.06, 1.  , 1.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 3.  , 1.  , 1.  , 0.  , 4.  ],
       [0.  , 0.  , 1.  , 3.  , 1.  , 1.  , 1.  , 2.  ],
       [0.  , 1.  , 0.  , 3.5 , 1.  , 1.  , 0.  , 3.  ],
       [0.  , 0.  , 1.  , 1.5 , 0.  , 0.  , 1.  , 2.  ],
       [1.  , 0.  , 0.  , 3.  , 1.  , 1.  , 0.  , 5.  ],
       [0.  , 0.  , 1.  , 2.  , 0.  , 1.  , 1.  , 2.  ],
       [1.  , 0.  , 0.  , 1.97, 1.  , 0.  , 0.  , 2.  ],
       [0.  , 0.  , 0.  , 3.5 , 1.  , 0.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 2.  , 1.  , 0.  , 0.  , 2.  ],
       [0.  , 0.  , 1.  , 1.73, 1.  , 0.  , 1.  , 2.  ],
       [1.  , 0.  , 0.  , 3.48, 0.  , 1.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 4.08, 1.  , 0.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 6.  , 1.  , 0.  , 0.  , 4.  ],
       [0.  , 0.  , 1.  , 3.23, 0.  , 1.  , 1.  , 3.  ],
       [0.  , 1.  , 0.  , 4.71, 1.  , 0.  , 0.  , 4.  ],
       [1.  , 0.  , 0.  , 1.  , 0.  , 0.  , 0.  , 1.  ],
       [0.  , 0.  , 0.  , 3.  , 1.  , 1.  , 0.  , 2.  ],
       [0.  , 0.  , 1.  , 2.01, 0.  , 1.  , 1.  , 2.  ],
       [0.  , 0.  , 1.  , 2.  , 1.  , 0.  , 1.  , 2.  ],
       [0.  , 1.  , 0.  , 3.11, 1.  , 1.  , 0.  , 2.  ],
       [0.  , 0.  , 0.  , 2.  , 0.  , 1.  , 1.  , 2.  ],
       [0.  , 1.  , 0.  , 3.  , 1.  , 0.  , 0.  , 2.  ]])

In [20]:
# SVR -- Support Vector Regression

from sklearn.svm import SVR

svr = SVR()

In [21]:
svr.fit(X_train, y_train)

SVR()

In [22]:
y_pred = svr.predict(X_test)

In [23]:
from sklearn.metrics import r2_score, mean_absolute_error

print(f'MAE: {mean_absolute_error(y_test, y_pred)}')
print(f'R2 Score: {r2_score(y_test, y_pred)}')

MAE: 4.1486423210190235
R2 Score: 0.46028114561159283

In [24]:
## Hyperparameter Tuning Using GridSearchCV

from sklearn.model_selection import GridSearchCV

In [25]:
param_grid = {
    'C': [1, 10, 100, 1000, 10000],
    'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
    'kernel' : ['linear', 'rbf', 'sigmoid'],
    'epsilon' : [0.001, 0.01, 0.1, 1,],
}

In [26]:
grid = GridSearchCV(SVR(), param_grid=param_grid, refit=True, verbose=3, cv=3)

grid.fit(X_train, y_train)

Fitting 3 folds for each of 300 candidates, totalling 900 fits
[CV 1/3] END C=1, epsilon=0.001, gamma=1, kernel=linear;, score=0.277 total time=   0.0s
[CV 2/3] END C=1, epsilon=0.001, gamma=1, kernel=linear;, score=0.699 total time=   0.0s
[CV 3/3] END C=1, epsilon=0.001, gamma=1, kernel=linear;, score=0.533 total time=   0.0s
[CV 1/3] END C=1, epsilon=0.001, gamma=1, kernel=rbf;, score=0.056 total time=   0.0s
[CV 2/3] END C=1, epsilon=0.001, gamma=1, kernel=rbf;, score=0.061 total time=   0.0s
[CV 3/3] END C=1, epsilon=0.001, gamma=1, kernel=rbf;, score=0.129 total time=   0.0s
[CV 1/3] END C=1, epsilon=0.001, gamma=1, kernel=sigmoid;, score=-0.055 total time=   0.0s
[CV 2/3] END C=1, epsilon=0.001, gamma=1, kernel=sigmoid;, score=-0.123 total time=   0.0s
[CV 3/3] END C=1, epsilon=0.001, gamma=1, kernel=sigmoid;, score=-0.032 total time=   0.0s
[CV 1/3] END C=1, epsilon=0.001, gamma=0.1, kernel=linear;, score=0.277 total time=   0.0s
[CV 2/3] END C=1, epsilon=0.001, gamma=0.1, kernel=linear;, score=0.699 total time=   0.0s
[CV 3/3] END C=1, epsilon=0.001, gamma=0.1, kernel=linear;, score=0.533 total time=   0.0s
[CV 1/3] END C=1, epsilon=0.001, gamma=0.1, kernel=rbf;, score=0.245 total time=   0.0s
[CV 2/3] END C=1, epsilon=0.001, gamma=0.1, kernel=rbf;, score=0.390 total time=   0.0s
[CV 3/3] END C=1, epsilon=0.001, gamma=0.1, kernel=rbf;, score=0.455 total time=   0.0s
[CV 1/3] END C=1, epsilon=0.001, gamma=0.1, kernel=sigmoid;, score=-0.497 total time=   0.0s
[CV 2/3] END C=1, epsilon=0.001, gamma=0.1, kernel=sigmoid;, score=-0.617 total time=   0.0s
[CV 3/3] END C=1, epsilon=0.001, gamma=0.1, kernel=sigmoid;, score=-0.537 total time=   0.0s
[CV 1/3] END C=1, epsilon=0.001, gamma=0.01, kernel=linear;, score=0.277 total time=   0.0s
[CV 2/3] END C=1, epsilon=0.001, gamma=0.01, kernel=linear;, score=0.699 total time=   0.0s
[CV 3/3] END C=1, epsilon=0.001, gamma=0.01, kernel=linear;, score=0.533 total time=   0.0s
[CV 1/3] END C=1, epsilon=0.001, gamma=0.01, kernel=rbf;, score=0.149 total time=   0.0s
[CV 2/3] END C=1, epsilon=0.001, gamma=0.01, kernel=rbf;, score=0.194 total time=   0.0s
[CV 3/3] END C=1, epsilon=0.001, gamma=0.01, kernel=rbf;, score=0.268 total time=   0.0s
[CV 1/3] END C=1, epsilon=0.001, gamma=0.01, kernel=sigmoid;, score=0.085 total time=   0.0s
[CV 2/3] END C=1, epsilon=0.001, gamma=0.01, kernel=sigmoid;, score=0.084 total time=   0.0s
[CV 3/3] END C=1, epsilon=0.001, gamma=0.01, kernel=sigmoid;, score=0.149 total time=   0.0s
[CV 1/3] END C=1, epsilon=0.001, gamma=0.001, kernel=linear;, score=0.277 total time=   0.0s
[CV 2/3] END C=1, epsilon=0.001, gamma=0.001, kernel=linear;, score=0.699 total time=   0.0s
[CV 3/3] END C=1, epsilon=0.001, gamma=0.001, kernel=linear;, score=0.533 total time=   0.0s
[CV 1/3] END C=1, epsilon=0.001, gamma=0.001, kernel=rbf;, score=-0.015 total time=   0.0s
[CV 2/3] END C=1, epsilon=0.001, gamma=0.001, kernel=rbf;, score=-0.070 total time=   0.0s
[CV 3/3] END C=1, epsilon=0.001, gamma=0.001, kernel=rbf;, score=0.021 total time=   0.0s
[CV 1/3] END C=1, epsilon=0.001, gamma=0.001, kernel=sigmoid;, score=-0.034 total time=   0.0s
[CV 2/3] END C=1, epsilon=0.001, gamma=0.001, kernel=sigmoid;, score=-0.095 total time=   0.0s
[CV 3/3] END C=1, epsilon=0.001, gamma=0.001, kernel=sigmoid;, score=-0.003 total time=   0.0s
[CV 1/3] END C=1, epsilon=0.001, gamma=0.0001, kernel=linear;, score=0.277 total time=   0.0s
[CV 2/3] END C=1, epsilon=0.001, gamma=0.0001, kernel=linear;, score=0.699 total time=   0.0s
[CV 3/3] END C=1, epsilon=0.001, gamma=0.0001, kernel=linear;, score=0.533 total time=   0.0s
[CV 1/3] END C=1, epsilon=0.001, gamma=0.0001, kernel=rbf;, score=-0.051 total time=   0.0s
[CV 2/3] END C=1, epsilon=0.001, gamma=0.0001, kernel=rbf;, score=-0.117 total time=   0.0s
[CV 3/3] END C=1, epsilon=0.001, gamma=0.0001, kernel=rbf;, score=-0.026 total time=   0.0s
[CV 1/3] END C=1, epsilon=0.001, gamma=0.0001, kernel=sigmoid;, score=-0.053 total time=   0.0s
[CV 2/3] END C=1, epsilon=0.001, gamma=0.0001, kernel=sigmoid;, score=-0.120 total time=   0.0s
[CV 3/3] END C=1, epsilon=0.001, gamma=0.0001, kernel=sigmoid;, score=-0.029 total time=   0.0s
[CV 1/3] END C=1, epsilon=0.01, gamma=1, kernel=linear;, score=0.277 total time=   0.0s
[CV 2/3] END C=1, epsilon=0.01, gamma=1, kernel=linear;, score=0.699 total time=   0.0s
[CV 3/3] END C=1, epsilon=0.01, gamma=1, kernel=linear;, score=0.533 total time=   0.0s
[CV 1/3] END C=1, epsilon=0.01, gamma=1, kernel=rbf;, score=0.056 total time=   0.0s
[CV 2/3] END C=1, epsilon=0.01, gamma=1, kernel=rbf;, score=0.061 total time=   0.0s
[CV 3/3] END C=1, epsilon=0.01, gamma=1, kernel=rbf;, score=0.129 total time=   0.0s
[CV 1/3] END C=1, epsilon=0.01, gamma=1, kernel=sigmoid;, score=-0.055 total time=   0.0s
[CV 2/3] END C=1, epsilon=0.01, gamma=1, kernel=sigmoid;, score=-0.123 total time=   0.0s
[CV 3/3] END C=1, epsilon=0.01, gamma=1, kernel=sigmoid;, score=-0.032 total time=   0.0s
[CV 1/3] END C=1, epsilon=0.01, gamma=0.1, kernel=linear;, score=0.277 total time=   0.0s
[CV 2/3] END C=1, epsilon=0.01, gamma=0.1, kernel=linear;, score=0.699 total time=   0.0s
[CV 3/3] END C=1, epsilon=0.01, gamma=0.1, kernel=linear;, score=0.533 total time=   0.0s
[CV 1/3] END C=1, epsilon=0.01, gamma=0.1, kernel=rbf;, score=0.245 total time=   0.0s
[CV 2/3] END C=1, epsilon=0.01, gamma=0.1, kernel=rbf;, score=0.390 total time=   0.0s
[CV 3/3] END C=1, epsilon=0.01, gamma=0.1, kernel=rbf;, score=0.455 total time=   0.0s
[CV 1/3] END C=1, epsilon=0.01, gamma=0.1, kernel=sigmoid;, score=-0.495 total time=   0.0s
[CV 2/3] END C=1, epsilon=0.01, gamma=0.1, kernel=sigmoid;, score=-0.617 total time=   0.0s
[CV 3/3] END C=1, epsilon=0.01, gamma=0.1, kernel=sigmoid;, score=-0.537 total time=   0.0s
[CV 1/3] END C=1, epsilon=0.01, gamma=0.01, kernel=linear;, score=0.277 total time=   0.0s
[CV 2/3] END C=1, epsilon=0.01, gamma=0.01, kernel=linear;, score=0.699 total time=   0.0s
[CV 3/3] END C=1, epsilon=0.01, gamma=0.01, kernel=linear;, score=0.533 total time=   0.0s
[CV 1/3] END C=1, epsilon=0.01, gamma=0.01, kernel=rbf;, score=0.149 total time=   0.0s
[CV 2/3] END C=1, epsilon=0.01, gamma=0.01, kernel=rbf;, score=0.194 total time=   0.0s
[CV 3/3] END C=1, epsilon=0.01, gamma=0.01, kernel=rbf;, score=0.268 total time=   0.0s
[CV 1/3] END C=1, epsilon=0.01, gamma=0.01, kernel=sigmoid;, score=0.085 total time=   0.0s
[CV 2/3] END C=1, epsilon=0.01, gamma=0.01, kernel=sigmoid;, score=0.084 total time=   0.0s
[CV 3/3] END C=1, epsilon=0.01, gamma=0.01, kernel=sigmoid;, score=0.148 total time=   0.0s
[CV 1/3] END C=1, epsilon=0.01, gamma=0.001, kernel=linear;, score=0.277 total time=   0.0s
[CV 2/3] END C=1, epsilon=0.01, gamma=0.001, kernel=linear;, score=0.699 total time=   0.0s
[CV 3/3] END C=1, epsilon=0.01, gamma=0.001, kernel=linear;, score=0.533 total time=   0.0s
[CV 1/3] END C=1, epsilon=0.01, gamma=0.001, kernel=rbf;, score=-0.015 total time=   0.0s
[CV 2/3] END C=1, epsilon=0.01, gamma=0.001, kernel=rbf;, score=-0.070 total time=   0.0s
[CV 3/3] END C=1, epsilon=0.01, gamma=0.001, kernel=rbf;, score=0.021 total time=   0.0s
[CV 1/3] END C=1, epsilon=0.01, gamma=0.001, kernel=sigmoid;, score=-0.034 total time=   0.0s
[CV 2/3] END C=1, epsilon=0.01, gamma=0.001, kernel=sigmoid;, score=-0.095 total time=   0.0s
[CV 3/3] END C=1, epsilon=0.01, gamma=0.001, kernel=sigmoid;, score=-0.003 total time=   0.0s
[CV 1/3] END C=1, epsilon=0.01, gamma=0.0001, kernel=linear;, score=0.277 total time=   0.0s
[CV 2/3] END C=1, epsilon=0.01, gamma=0.0001, kernel=linear;, score=0.699 total time=   0.0s
[CV 3/3] END C=1, epsilon=0.01, gamma=0.0001, kernel=linear;, score=0.533 total time=   0.0s
[CV 1/3] END C=1, epsilon=0.01, gamma=0.0001, kernel=rbf;, score=-0.051 total time=   0.0s
[CV 2/3] END C=1, epsilon=0.01, gamma=0.0001, kernel=rbf;, score=-0.117 total time=   0.0s
[CV 3/3] END C=1, epsilon=0.01, gamma=0.0001, kernel=rbf;, score=-0.026 total time=   0.0s
[CV 1/3] END C=1, epsilon=0.01, gamma=0.0001, kernel=sigmoid;, score=-0.053 total time=   0.0s
[CV 2/3] END C=1, epsilon=0.01, gamma=0.0001, kernel=sigmoid;, score=-0.120 total time=   0.0s
[CV 3/3] END C=1, epsilon=0.01, gamma=0.0001, kernel=sigmoid;, score=-0.029 total time=   0.0s
[CV 1/3] END C=1, epsilon=0.1, gamma=1, kernel=linear;, score=0.282 total time=   0.0s
[CV 2/3] END C=1, epsilon=0.1, gamma=1, kernel=linear;, score=0.697 total time=   0.0s
[CV 3/3] END C=1, epsilon=0.1, gamma=1, kernel=linear;, score=0.530 total time=   0.0s
[CV 1/3] END C=1, epsilon=0.1, gamma=1, kernel=rbf;, score=0.058 total time=   0.0s
[CV 2/3] END C=1, epsilon=0.1, gamma=1, kernel=rbf;, score=0.060 total time=   0.0s
[CV 3/3] END C=1, epsilon=0.1, gamma=1, kernel=rbf;, score=0.130 total time=   0.0s
[CV 1/3] END C=1, epsilon=0.1, gamma=1, kernel=sigmoid;, score=-0.059 total time=   0.0s
[CV 2/3] END C=1, epsilon=0.1, gamma=1, kernel=sigmoid;, score=-0.123 total time=   0.0s
[CV 3/3] END C=1, epsilon=0.1, gamma=1, kernel=sigmoid;, score=-0.030 total time=   0.0s
[CV 1/3] END C=1, epsilon=0.1, gamma=0.1, kernel=linear;, score=0.282 total time=   0.0s
[CV 2/3] END C=1, epsilon=0.1, gamma=0.1, kernel=linear;, score=0.697 total time=   0.0s
[CV 3/3] END C=1, epsilon=0.1, gamma=0.1, kernel=linear;, score=0.530 total time=   0.0s
[CV 1/3] END C=1, epsilon=0.1, gamma=0.1, kernel=rbf;, score=0.248 total time=   0.0s
[CV 2/3] END C=1, epsilon=0.1, gamma=0.1, kernel=rbf;, score=0.389 total time=   0.0s
[CV 3/3] END C=1, epsilon=0.1, gamma=0.1, kernel=rbf;, score=0.452 total time=   0.0s
[CV 1/3] END C=1, epsilon=0.1, gamma=0.1, kernel=sigmoid;, score=-0.491 total time=   0.0s
[CV 2/3] END C=1, epsilon=0.1, gamma=0.1, kernel=sigmoid;, score=-0.617 total time=   0.0s
[CV 3/3] END C=1, epsilon=0.1, gamma=0.1, kernel=sigmoid;, score=-0.538 total time=   0.0s
[CV 1/3] END C=1, epsilon=0.1, gamma=0.01, kernel=linear;, score=0.282 total time=   0.0s
[CV 2/3] END C=1, epsilon=0.1, gamma=0.01, kernel=linear;, score=0.697 total time=   0.0s
[CV 3/3] END C=1, epsilon=0.1, gamma=0.01, kernel=linear;, score=0.530 total time=   0.0s
[CV 1/3] END C=1, epsilon=0.1, gamma=0.01, kernel=rbf;, score=0.154 total time=   0.0s
[CV 2/3] END C=1, epsilon=0.1, gamma=0.01, kernel=rbf;, score=0.201 total time=   0.0s
[CV 3/3] END C=1, epsilon=0.1, gamma=0.01, kernel=rbf;, score=0.272 total time=   0.0s
[CV 1/3] END C=1, epsilon=0.1, gamma=0.01, kernel=sigmoid;, score=0.085 total time=   0.0s
[CV 2/3] END C=1, epsilon=0.1, gamma=0.01, kernel=sigmoid;, score=0.080 total time=   0.0s
[CV 3/3] END C=1, epsilon=0.1, gamma=0.01, kernel=sigmoid;, score=0.146 total time=   0.0s
[CV 1/3] END C=1, epsilon=0.1, gamma=0.001, kernel=linear;, score=0.282 total time=   0.0s
[CV 2/3] END C=1, epsilon=0.1, gamma=0.001, kernel=linear;, score=0.697 total time=   0.0s
[CV 3/3] END C=1, epsilon=0.1, gamma=0.001, kernel=linear;, score=0.530 total time=   0.0s
[CV 1/3] END C=1, epsilon=0.1, gamma=0.001, kernel=rbf;, score=-0.017 total time=   0.0s
[CV 2/3] END C=1, epsilon=0.1, gamma=0.001, kernel=rbf;, score=-0.068 total time=   0.0s
[CV 3/3] END C=1, epsilon=0.1, gamma=0.001, kernel=rbf;, score=0.020 total time=   0.0s
[CV 1/3] END C=1, epsilon=0.1, gamma=0.001, kernel=sigmoid;, score=-0.037 total time=   0.0s
[CV 2/3] END C=1, epsilon=0.1, gamma=0.001, kernel=sigmoid;, score=-0.095 total time=   0.0s
[CV 3/3] END C=1, epsilon=0.1, gamma=0.001, kernel=sigmoid;, score=-0.004 total time=   0.0s
[CV 1/3] END C=1, epsilon=0.1, gamma=0.0001, kernel=linear;, score=0.282 total time=   0.0s
[CV 2/3] END C=1, epsilon=0.1, gamma=0.0001, kernel=linear;, score=0.697 total time=   0.0s
[CV 3/3] END C=1, epsilon=0.1, gamma=0.0001, kernel=linear;, score=0.530 total time=   0.0s
[CV 1/3] END C=1, epsilon=0.1, gamma=0.0001, kernel=rbf;, score=-0.054 total time=   0.0s
[CV 2/3] END C=1, epsilon=0.1, gamma=0.0001, kernel=rbf;, score=-0.117 total time=   0.0s
[CV 3/3] END C=1, epsilon=0.1, gamma=0.0001, kernel=rbf;, score=-0.024 total time=   0.0s
[CV 1/3] END C=1, epsilon=0.1, gamma=0.0001, kernel=sigmoid;, score=-0.056 total time=   0.0s
[CV 2/3] END C=1, epsilon=0.1, gamma=0.0001, kernel=sigmoid;, score=-0.120 total time=   0.0s
[CV 3/3] END C=1, epsilon=0.1, gamma=0.0001, kernel=sigmoid;, score=-0.027 total time=   0.0s
[CV 1/3] END C=1, epsilon=1, gamma=1, kernel=linear;, score=0.302 total time=   0.0s
[CV 2/3] END C=1, epsilon=1, gamma=1, kernel=linear;, score=0.708 total time=   0.0s
[CV 3/3] END C=1, epsilon=1, gamma=1, kernel=linear;, score=0.548 total time=   0.0s
[CV 1/3] END C=1, epsilon=1, gamma=1, kernel=rbf;, score=0.062 total time=   0.0s
[CV 2/3] END C=1, epsilon=1, gamma=1, kernel=rbf;, score=0.074 total time=   0.0s
[CV 3/3] END C=1, epsilon=1, gamma=1, kernel=rbf;, score=0.127 total time=   0.0s
[CV 1/3] END C=1, epsilon=1, gamma=1, kernel=sigmoid;, score=-0.060 total time=   0.0s
[CV 2/3] END C=1, epsilon=1, gamma=1, kernel=sigmoid;, score=-0.124 total time=   0.0s
[CV 3/3] END C=1, epsilon=1, gamma=1, kernel=sigmoid;, score=-0.031 total time=   0.0s
[CV 1/3] END C=1, epsilon=1, gamma=0.1, kernel=linear;, score=0.302 total time=   0.0s
[CV 2/3] END C=1, epsilon=1, gamma=0.1, kernel=linear;, score=0.708 total time=   0.0s
[CV 3/3] END C=1, epsilon=1, gamma=0.1, kernel=linear;, score=0.548 total time=   0.0s
[CV 1/3] END C=1, epsilon=1, gamma=0.1, kernel=rbf;, score=0.253 total time=   0.0s
[CV 2/3] END C=1, epsilon=1, gamma=0.1, kernel=rbf;, score=0.378 total time=   0.0s
[CV 3/3] END C=1, epsilon=1, gamma=0.1, kernel=rbf;, score=0.435 total time=   0.0s
[CV 1/3] END C=1, epsilon=1, gamma=0.1, kernel=sigmoid;, score=-0.476 total time=   0.0s
[CV 2/3] END C=1, epsilon=1, gamma=0.1, kernel=sigmoid;, score=-0.621 total time=   0.0s
[CV 3/3] END C=1, epsilon=1, gamma=0.1, kernel=sigmoid;, score=-0.544 total time=   0.0s
[CV 1/3] END C=1, epsilon=1, gamma=0.01, kernel=linear;, score=0.302 total time=   0.0s
[CV 2/3] END C=1, epsilon=1, gamma=0.01, kernel=linear;, score=0.708 total time=   0.0s
[CV 3/3] END C=1, epsilon=1, gamma=0.01, kernel=linear;, score=0.548 total time=   0.0s
[CV 1/3] END C=1, epsilon=1, gamma=0.01, kernel=rbf;, score=0.174 total time=   0.0s
[CV 2/3] END C=1, epsilon=1, gamma=0.01, kernel=rbf;, score=0.231 total time=   0.0s
[CV 3/3] END C=1, epsilon=1, gamma=0.01, kernel=rbf;, score=0.276 total time=   0.0s
[CV 1/3] END C=1, epsilon=1, gamma=0.01, kernel=sigmoid;, score=0.087 total time=   0.0s
[CV 2/3] END C=1, epsilon=1, gamma=0.01, kernel=sigmoid;, score=0.080 total time=   0.0s
[CV 3/3] END C=1, epsilon=1, gamma=0.01, kernel=sigmoid;, score=0.159 total time=   0.0s
[CV 1/3] END C=1, epsilon=1, gamma=0.001, kernel=linear;, score=0.302 total time=   0.0s
[CV 2/3] END C=1, epsilon=1, gamma=0.001, kernel=linear;, score=0.708 total time=   0.0s
[CV 3/3] END C=1, epsilon=1, gamma=0.001, kernel=linear;, score=0.548 total time=   0.0s
[CV 1/3] END C=1, epsilon=1, gamma=0.001, kernel=rbf;, score=-0.021 total time=   0.0s
[CV 2/3] END C=1, epsilon=1, gamma=0.001, kernel=rbf;, score=-0.075 total time=   0.0s
[CV 3/3] END C=1, epsilon=1, gamma=0.001, kernel=rbf;, score=0.016 total time=   0.0s
[CV 1/3] END C=1, epsilon=1, gamma=0.001, kernel=sigmoid;, score=-0.043 total time=   0.0s
[CV 2/3] END C=1, epsilon=1, gamma=0.001, kernel=sigmoid;, score=-0.099 total time=   0.0s
[CV 3/3] END C=1, epsilon=1, gamma=0.001, kernel=sigmoid;, score=-0.008 total time=   0.0s
[CV 1/3] END C=1, epsilon=1, gamma=0.0001, kernel=linear;, score=0.302 total time=   0.0s
[CV 2/3] END C=1, epsilon=1, gamma=0.0001, kernel=linear;, score=0.708 total time=   0.0s
[CV 3/3] END C=1, epsilon=1, gamma=0.0001, kernel=linear;, score=0.548 total time=   0.0s
[CV 1/3] END C=1, epsilon=1, gamma=0.0001, kernel=rbf;, score=-0.057 total time=   0.0s
[CV 2/3] END C=1, epsilon=1, gamma=0.0001, kernel=rbf;, score=-0.118 total time=   0.0s
[CV 3/3] END C=1, epsilon=1, gamma=0.0001, kernel=rbf;, score=-0.027 total time=   0.0s
[CV 1/3] END C=1, epsilon=1, gamma=0.0001, kernel=sigmoid;, score=-0.058 total time=   0.0s
[CV 2/3] END C=1, epsilon=1, gamma=0.0001, kernel=sigmoid;, score=-0.121 total time=   0.0s
[CV 3/3] END C=1, epsilon=1, gamma=0.0001, kernel=sigmoid;, score=-0.029 total time=   0.0s
[CV 1/3] END C=10, epsilon=0.001, gamma=1, kernel=linear;, score=0.301 total time=   0.0s
[CV 2/3] END C=10, epsilon=0.001, gamma=1, kernel=linear;, score=0.695 total time=   0.0s
[CV 3/3] END C=10, epsilon=0.001, gamma=1, kernel=linear;, score=0.486 total time=   0.0s
[CV 1/3] END C=10, epsilon=0.001, gamma=1, kernel=rbf;, score=0.140 total time=   0.0s
[CV 2/3] END C=10, epsilon=0.001, gamma=1, kernel=rbf;, score=0.380 total time=   0.0s
[CV 3/3] END C=10, epsilon=0.001, gamma=1, kernel=rbf;, score=0.307 total time=   0.0s
[CV 1/3] END C=10, epsilon=0.001, gamma=1, kernel=sigmoid;, score=-0.057 total time=   0.0s
[CV 2/3] END C=10, epsilon=0.001, gamma=1, kernel=sigmoid;, score=-0.123 total time=   0.0s
[CV 3/3] END C=10, epsilon=0.001, gamma=1, kernel=sigmoid;, score=-0.033 total time=   0.0s
[CV 1/3] END C=10, epsilon=0.001, gamma=0.1, kernel=linear;, score=0.301 total time=   0.0s
[CV 2/3] END C=10, epsilon=0.001, gamma=0.1, kernel=linear;, score=0.695 total time=   0.0s
[CV 3/3] END C=10, epsilon=0.001, gamma=0.1, kernel=linear;, score=0.486 total time=   0.0s
[CV 1/3] END C=10, epsilon=0.001, gamma=0.1, kernel=rbf;, score=0.275 total time=   0.0s
[CV 2/3] END C=10, epsilon=0.001, gamma=0.1, kernel=rbf;, score=0.499 total time=   0.0s
[CV 3/3] END C=10, epsilon=0.001, gamma=0.1, kernel=rbf;, score=0.475 total time=   0.0s
[CV 1/3] END C=10, epsilon=0.001, gamma=0.1, kernel=sigmoid;, score=-16.720 total time=   0.0s
[CV 2/3] END C=10, epsilon=0.001, gamma=0.1, kernel=sigmoid;, score=-18.383 total time=   0.0s
[CV 3/3] END C=10, epsilon=0.001, gamma=0.1, kernel=sigmoid;, score=-18.302 total time=   0.0s
[CV 1/3] END C=10, epsilon=0.001, gamma=0.01, kernel=linear;, score=0.301 total time=   0.0s
[CV 2/3] END C=10, epsilon=0.001, gamma=0.01, kernel=linear;, score=0.695 total time=   0.0s
[CV 3/3] END C=10, epsilon=0.001, gamma=0.01, kernel=linear;, score=0.486 total time=   0.0s
[CV 1/3] END C=10, epsilon=0.001, gamma=0.01, kernel=rbf;, score=0.274 total time=   0.0s
[CV 2/3] END C=10, epsilon=0.001, gamma=0.01, kernel=rbf;, score=0.638 total time=   0.0s
[CV 3/3] END C=10, epsilon=0.001, gamma=0.01, kernel=rbf;, score=0.530 total time=   0.0s
[CV 1/3] END C=10, epsilon=0.001, gamma=0.01, kernel=sigmoid;, score=0.266 total time=   0.0s
[CV 2/3] END C=10, epsilon=0.001, gamma=0.01, kernel=sigmoid;, score=0.623 total time=   0.0s
[CV 3/3] END C=10, epsilon=0.001, gamma=0.01, kernel=sigmoid;, score=0.518 total time=   0.0s
[CV 1/3] END C=10, epsilon=0.001, gamma=0.001, kernel=linear;, score=0.301 total time=   0.0s
[CV 2/3] END C=10, epsilon=0.001, gamma=0.001, kernel=linear;, score=0.695 total time=   0.0s
[CV 3/3] END C=10, epsilon=0.001, gamma=0.001, kernel=linear;, score=0.486 total time=   0.0s
[CV 1/3] END C=10, epsilon=0.001, gamma=0.001, kernel=rbf;, score=0.176 total time=   0.0s
[CV 2/3] END C=10, epsilon=0.001, gamma=0.001, kernel=rbf;, score=0.248 total time=   0.0s
[CV 3/3] END C=10, epsilon=0.001, gamma=0.001, kernel=rbf;, score=0.306 total time=   0.0s
[CV 1/3] END C=10, epsilon=0.001, gamma=0.001, kernel=sigmoid;, score=0.103 total time=   0.0s
[CV 2/3] END C=10, epsilon=0.001, gamma=0.001, kernel=sigmoid;, score=0.125 total time=   0.0s
[CV 3/3] END C=10, epsilon=0.001, gamma=0.001, kernel=sigmoid;, score=0.178 total time=   0.0s
[CV 1/3] END C=10, epsilon=0.001, gamma=0.0001, kernel=linear;, score=0.301 total time=   0.0s
[CV 2/3] END C=10, epsilon=0.001, gamma=0.0001, kernel=linear;, score=0.695 total time=   0.0s
[CV 3/3] END C=10, epsilon=0.001, gamma=0.0001, kernel=linear;, score=0.486 total time=   0.0s
[CV 1/3] END C=10, epsilon=0.001, gamma=0.0001, kernel=rbf;, score=-0.015 total time=   0.0s
[CV 2/3] END C=10, epsilon=0.001, gamma=0.0001, kernel=rbf;, score=-0.068 total time=   0.0s

GridSearchCV(cv=3, estimator=SVR(),
             param_grid={'C': [1, 10, 100, 1000, 10000],
                         'epsilon': [0.001, 0.01, 0.1, 1],
                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
                         'kernel': ['linear', 'rbf', 'sigmoid']},
             verbose=3)

In [27]:
grid.best_params_

{'C': 10000, 'epsilon': 1, 'gamma': 0.0001, 'kernel': 'rbf'}

In [28]:
grid.best_score_

np.float64(0.5210793663308305)

In [29]:
svr = SVR(C=10000, epsilon= 1, gamma= 0.0001, kernel ='rbf').fit(X_train, y_train)

In [30]:
y_pred = svr.predict(X_test)
print(f'MAE: {mean_absolute_error(y_test, y_pred)}')
print(f'R2 Score: {r2_score(y_test, y_pred)}')

MAE: 3.921852079914249
R2 Score: 0.5308712557661617